[package]
name = "train-data-read"
version = "0.1.0"
authors = ["吕晓骏 <lvxiaojun@qutoutiao.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parquet = "0.4"
